### ISSUE TITLE
Xcode 8 GM

### ISSUE THREAD

**Issue by maciekish** [cyanzhong/Dotify#1]
Hi,
This doesnt compile in Xcode 8 GM, when i fix all the issues it still doesnt appear in the menu. What's wrong?

**Comment by cyanzhong** [comment]
Because you must sign every targets (app & extensions) with your developer certificate (after Xcode 8.0 Beta 6)

**Comment by cyanzhong** [comment]
<img width="300" alt="snapshot" src="https://cloud.githubusercontent.com/assets/6745066/18417699/d65e4aca-7869-11e6-85f3-cd1eafec0b4d.png">
